"""Copy the rendered map sprites into the client and record their heights.

Usage: python -I tools/art/kenney-props-post.py <render-dir>

<render-dir> is the out-dir of render-kenney.py run with kenney-props.json. Each
sprite is palette-reduced (the art is flat-shaded, 256 colours are plenty and the files
shrink about 3x for school networks) and copied to apps/client/public/art/kenney/props/.
apps/client/src/map/kenney-props.ts gets the canvas geometry and how high each
sprite reaches above the tile centre, so the map can put the building badge on top.
"""
import json
import os
import sys

from PIL import Image

render_dir = sys.argv[1]
here = os.path.dirname(os.path.abspath(__file__))
repo = os.path.dirname(os.path.dirname(here))
spec = json.load(open(os.path.join(here, 'kenney-props.json'), encoding='utf-8'))
out = os.path.join(repo, 'apps', 'client', 'public', 'art', 'kenney', 'props')
os.makedirs(out, exist_ok=True)

width, height = spec['canvas']
origin_x, origin_y = spec['origin']
tops = {}
for sprite in spec['sprites']:
    name = sprite['name']
    image = Image.open(os.path.join(render_dir, name + '.png')).convert('RGBA')
    assert image.size == (width, height), (name, image.size)
    alpha = image.getchannel('A')
    top_row = next(y for y in range(height) if max(alpha.crop((0, y, width, y + 1)).getdata()) > 8)
    tops[name] = origin_y - top_row
    image.quantize(256, method=Image.Quantize.FASTOCTREE, dither=Image.Dither.NONE).save(
        os.path.join(out, name + '.png'), optimize=True
    )

lines = [
    '// Generated by tools/art/kenney-props-post.py from tools/art/kenney-props.json. Do not edit.',
    '',
    "/** Map sprite canvas in sprite pixels: size, the tile centre on it, and a 1 x 1 tile's width. */",
    'export const PROP_CANVAS = {',
    f'  width: {width},',
    f'  height: {height},',
    f'  originX: {origin_x},',
    f'  originY: {origin_y},',
    f'  tilePx: {spec["tilePx"]},',
    '} as const;',
    '',
    '/** How far each sprite reaches above the tile centre, in sprite pixels (badge placement). */',
    'export const PROP_TOPS: Readonly<Record<string, number>> = {',
    *[f"  '{name}': {top}," for name, top in tops.items()],
    '};',
    '',
]
with open(os.path.join(repo, 'apps', 'client', 'src', 'map', 'kenney-props.ts'), 'w', encoding='utf-8', newline='\n') as f:
    f.write('\n'.join(lines))
print(f'copied {len(tops)} sprites to {out}')
