// Generated by tools/art/kenney-buildings-post.py from tools/art/kenney-buildings.json. Do not edit.

/** Building sprite canvas in sprite pixels: size, the tile centre on it, and a 1 x 1 tile's width. */
export const BUILDING_CANVAS = {
  width: 320,
  height: 400,
  originX: 160,
  originY: 330,
  tilePx: 264,
} as const;

/** How far each sprite reaches above the tile centre, in sprite pixels (badge placement). */
export const BUILDING_TOPS: Readonly<Record<string, number>> = {
  'shelter-1': 142,
  'shelter-2': 144,
  'shelter-3': 245,
  'school-1': 170,
  'school-2': 181,
  'school-3': 272,
  'workshop-1': 102,
  'workshop-2': 174,
  'workshop-3': 231,
  'gathering-1': 60,
  'gathering-2': 180,
  'gathering-3': 159,
};
