// Generated by tools/art/kenney-props-post.py from tools/art/kenney-props.json. Do not edit.

/** Map sprite canvas in sprite pixels: size, the tile centre on it, and a 1 x 1 tile's width. */
export const PROP_CANVAS = {
  width: 320,
  height: 400,
  originX: 160,
  originY: 330,
  tilePx: 264,
} as const;

/** How far each sprite reaches above the tile centre, in sprite pixels (badge placement). */
export const PROP_TOPS: Readonly<Record<string, number>> = {
  'shelter-1': 79,
  'shelter-2': 108,
  'shelter-3': 170,
  'school-1': 128,
  'school-2': 127,
  'school-3': 183,
  'workshop-1': 67,
  'workshop-2': 137,
  'workshop-3': 162,
  'gathering-1': 46,
  'gathering-2': 137,
  'gathering-3': 129,
  'field-0': 83,
  'field-1': 83,
  'field-2': 83,
  'field-3': 103,
  'forest-1a': 140,
  'forest-1b': 128,
  'forest-2a': 140,
  'forest-2b': 128,
  'forest-3a': 140,
  'forest-3b': 128,
  'rock-a': 94,
  'rock-b': 82,
  'meadow-a': 53,
  'meadow-b': 53,
  'meadow-c': 53,
  'quarry': 96,
  'spring': 124,
  'boat': 75,
};
